cars/cars/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from icars.views import *
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^$', mainpage),
    url(r'^admin/', admin.site.urls),
    url(r'^icars/', include('icars.urls', namespace='icars')),
    url(r'^login/$',	login,	name='login'),
	url(r'^logout/$',	logout,	name='logout')
    #url(r'^registration/$',	registration,	name='registration')
]

cars/icars/urls.py
from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import UpdateView, ListView
from django.views.generic.base import RedirectView

from models import *
from views import *

urlpatterns = [
    # home page
    url(r'^$',
        RedirectView.as_view(url=reverse_lazy('icars:brand_list', kwargs={'extension': 'html'})),
        name='home_page'),


    url(r'^marques\.(?P<extension>(json|xml|html))$',
        MarcaList.as_view(),
        name='brand_list'),
    # brand details: /icars/marques/1
    url(r'^marques/(?P<pk>\d+)(\.(?P<extension>(json|xml|html)))?$',
        MarcaDetail.as_view(),
        name='brand_detail'),
    # Create a brand: /icars/marques/create/
    url(r'^marques/create/$',
        MarcaCreate.as_view(),
        name='brand_create'),
    # Edit a brand: /icars/marques/1/edit/
    url(r'^marques/(?P<pk>\d+)/edit/$',
        UpdateView.as_view(
        model = Marca,
        template_name='icars/form.html',
        form_class = MarcaForm),
        name='brand_edit'),


    # List all models: /icars/models.json
    url(r'^models\.(?P<extension>(json|xml|html))$',
        ModelList.as_view(),
        name='model_list'),

    url(r'^models/(?P<pk>\d+)(\.(?P<extension>(json|xml|html)))?$',
        ModelDetail.as_view(),
        name='model_detail'),
    # Create a model: /icars/models/create/
    url(r'^models/create/$',
        ModelCreate.as_view(),
        name='model_create'),
    # Edit a model: /icars/models/1/edit/
    url(r'^models/(?P<pk>\d+)/edit/$',
        UpdateView.as_view(
        model = Model,
        template_name='icars/form.html',
        form_class = ModelForm),
        name='model_edit'),


    # List all motors: /icars/motor.html
    url(r'^motor\.(?P<extension>(json|xml|html))$',
        MotorList.as_view(),
        name='motor_list'),
    # Detail of a motor: icars/motor/1.html
    url(r'^motor/(?P<pk>\d+)\.(?P<extension>(json|xml|html))?$',
        MotorDetail.as_view(),
        name='motor_detail'),
    # Create a motor: /icars/motor/create/
    url(r'^motor/create/$',
        MotorCreate.as_view(),
        name='motor_create'),
    # Edit a motor: /icars/motor/1/edit/
    url(r'^motor/(?P<pk>\d+)/edit/$',
        UpdateView.as_view(
        model = Motor,
        template_name='icars/form.html',
        form_class = MotorForm),
        name='motor_edit'),


    # List 10 styles : /icars/estil.json
    url(r'^estil\.(?P<extension>(json|xml|html))$',
        EstilList.as_view(),
        name='style_list'),
    # Detail of a style: /icars/estil/1.html
    url(r'^estil/(?P<pk>\d+)\.(?P<extension>(json|xml|html))?$',
        EstilDetail.as_view(),
        name='style_detail'),
    # Create a style: /icars/estil/create/
    url(r'^estil/create/$',
        EstilCreate.as_view(),
        name='style_create'),
    # Edit a model: /icars/estil/1/edit/
    url(r'^estil/(?P<pk>\d+)/edit/$',
        UpdateView.as_view(
        model = Estil,
        template_name='icars/form.html',
        form_class = EstilForm),
        name='style_edit'),

    # delete a motor /icars/motor/1/delete
    url(r'^motor/(?P<pk>\d+)/delete/$',
        MotorDelete.as_view(),
        name='motor_delete'),

    # delete a motor /icars/motor/1/delete
    url(r'^marques/(?P<pk>\d+)/delete/$',
        MarcaDelete.as_view(),
        name='marca_delete'),

    # delete a model /icars/model/1/delete
    url(r'^models/(?P<pk>\d+)/delete/$',
        ModelDelete.as_view(),
        name='model_delete'),

    # delete a style /icars/estil/1/delete
    url(r'^estil/(?P<pk>\d+)/delete/$',
        EstilDelete.as_view(),
        name='style_delete'),

]

cars/icars/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.


class Marca(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField()
    niceName = models.TextField()
    def __unicode__(self):
        return u"%s" % self.name

    def get_absolute_url(self):
        return reverse('icars:brand_detail', kwargs={'pk': self.pk})


class Model(models.Model):
    id = models.AutoField(primary_key=True)
    years = []
    name = models.TextField()
    niceName = models.TextField()
    marca = models.ForeignKey(Marca, null=True, related_name='models')

    def __unicode__(self):
        return u"%s" % self.name

    def get_absolute_url(self):
        return reverse('icars:model_detail', kwargs={'pk': self.pk})


class Year(models.Model):
    id = models.AutoField(primary_key=True)
    year = models.PositiveSmallIntegerField(default=1)


class Estil(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField()
    trim = models.TextField()

    def __unicode__(self):
        return u"%s" % self.name

    def get_absolute_url(self):
        return reverse('icars:style_detail', kwargs={'pk': self.pk})

    class Make:
        id = models.ForeignKey(Marca, on_delete=models.CASCADE)
        name = models.TextField()
        niceName = models.TextField()

    class Model:
        id = models.ForeignKey(Model, on_delete=models.CASCADE)
        name = models.TextField()
        niceName = models.TextField()

    class Year:
        id = models.ForeignKey(Year, on_delete=models.CASCADE)
        year = models.PositiveSmallIntegerField()

    class Submodel:
        body = models.TextField()
        fuel = models.TextField()
        tuner = models.TextField()
        modelName = models.TextField()
        niceName = models.TextField()


class Motor(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField()
    equipmentType = models.TextField(default="ENGINE")
    availability = models.TextField()
    compressionRatio = models.DecimalField(max_digits=7, decimal_places=5)
    cylinder = models.PositiveSmallIntegerField()
    size = models.DecimalField(max_digits=7, decimal_places=4)
    displacement = models.PositiveSmallIntegerField()
    configuration = models.TextField()
    fuelType = models.TextField()
    horsePower = models.PositiveSmallIntegerField()
    torque = models.PositiveSmallIntegerField()
    totalValues = models.PositiveSmallIntegerField()
    manufacturerEngineCode = models.TextField()
    typeN = models.TextField()
    code = models.TextField()
    compressorType = models.TextField()

    def __unicode__(self):
        return u"%s" % self.name

    def get_absolute_url(self):
        return reverse('icars:motor_detail', kwargs={'pk': self.pk})


class Transmission(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField()
    equipmentType = models.TextField(default="TRANSMISSION")
    availability = models.TextField()
    automaticType = models.TextField()
    transsmisionType = models.TextField()
    numberOfSpeeds = models.PositiveSmallIntegerField()
    motor = models.ForeignKey(Motor)

cars/icars/forms.py
from django.forms import ModelForm
from models import *


class MarcaForm(ModelForm):
    class Meta:
        model = Marca
        exclude = ('niceName',)


class ModelForm(ModelForm):
    class Meta:
        model = Model
        exclude = ('niceName', 'state', 'years',)


class MotorForm(ModelForm):
    class Meta:
        model = Motor
        exclude = ('availability',)


class EstilForm(ModelForm):
    class Meta:
        model = Estil
        exclude = ('trim', 'Submodel.niceName',)

cars/icars/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic import DetailView, ListView
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from models import Marca, Model, Motor, Year, Estil
from forms import *


def mainpage(request):
    return HttpResponse('CARS')


class MarcaList(ListView):
    model = Marca
    context_object_name = 'brand_list'
    template_name = 'icars/brand_list.html'


class MarcaCreate(CreateView):
    model = Marca
    template_name = 'icars/form.html'
    form_class = MarcaForm


class MarcaDetail(DetailView):
    model = Marca
    template_name = 'icars/brand_detail.html'


class MarcaDelete(DeleteView):
    model = Marca
    template_name = 'icars/delete.html'
    success_url = '/icars/marques.html'


class ModelList(ListView):
    model = Model


class ModelCreate(CreateView):
    model = Model
    template_name = 'icars/form.html'
    form_class = ModelForm


class ModelDetail(DetailView):
    model = Model
    template_name = 'icars/model_detail.html'


class ModelDelete(DeleteView):
    model = Model
    template_name = 'icars/delete.html'
    success_url = '/icars/models.html'


class EstilList(ListView):
    model = Estil
    context_object_name = 'style_list'
    template_name = 'icars/style_list.html'


class EstilCreate(CreateView):
    model = Estil
    template_name = 'icars/form.html'
    form_class = EstilForm


class EstilDetail(DetailView):
    model = Estil
    template_name = 'icars/style_detail.html'


class EstilDelete(DeleteView):
    model = Estil
    template_name = 'icars/delete.html'
    success_url = '/icars/estil.html'


class MotorList(ListView):
    model = Motor
    template_name = 'icars/motor_list.html'


class MotorCreate(CreateView):
    model = Motor
    template_name = 'icars/form.html'
    form_class = MotorForm


class MotorDetail(DetailView):
    model = Motor
    template_name = 'icars/motor_detail.html'


class MotorDelete(DeleteView):
    model = Motor
    template_name = 'icars/delete.html'
    success_url = '/icars/motor.html'

cars/icars/templates/icars/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
				<link	rel="stylesheet"
										href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"	/>
				<script	src="http://code.jquery.com/jquery-2.2.3.js"></script>
				<script	src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script> 
</head>
<body>
<div id="header">
    {% block header %}
        {% if user.username %}<p>User:	{{	user.username	}}	|
																<a	href="{%	url	'logout'	%}?next={{request.path}}">logout</a></p>
        {%	else	%}
        	<p><a	href="{%	url	'login'	%}?next={{request.path}}">login</a></p>
        {%	endif	%}
    {% endblock %}
</div>
<div id="sidebar">
    {% block sidebar %}<ul><li><a href="/icars">Home</a></li></ul>{% endblock %}
</div>
<div id="content">
    {% block content %}
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% endblock %}
</div>
<div id="footer">{% block footer %}{% endblock %}</div>
</body>
</html>

cars/icars/templates/icars/brand_detail.html
{% extends "icars/base.html" %}
{% block content %}
<span vocab= "http://schema.org/" typeof= "Product">
<h1>Name:</h1>
  <span property="name">{{ marca.name }}</span>
  <span rel="brand">
    <ul typeof="Brand">
    <p>
      <span property="name">, {{ marca.niceName }}</span>
    </p>
  </ul>
  </span>
  <span rel="model">
    <ul typeof="ProductModel">
    {% for model in marca.models.all %}
        <li><a>
            <span property="name">{{ model.name }}</span>
        </a></li>
    {% empty %}<li>Sorry, no models for this brand yet.</li>
    {% endfor %}
    </ul>
    </span>
</span>

{% endblock %}

cars/icars/templates/icars/brand_list.html
{% extends "icars/base.html" %}
{% block content %}
<h1>
    Marques
    {% if user %}(<a href="{% url 'icars:brand_create' %}">add</a>){% endif %}
</h1>
<ul>
    {% for marca in brand_list %}
        <li><a>
            {{ marca.name }} ({{ marca.id }})</a></li>
    {% empty %}<li>Sorry, no brands registered yet.</li>
    {% endfor %}
</ul>
{% endblock %}

cars/icars/templates/icars/form.html
{% extends "icars/base.html" %}
{% block content %}
    <form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}
<script>
  $(function()	{
    var	brands	=	["Opel",	"Toyota", "Ford",	"Peugeot",	"Nisan","Mercedes"];
    $(	"#id_brands"	).autocomplete({
      source:	brands
    });
  });
</script>

cars/icars/templates/icars/marca_detail.html
{% extends "icars/base.html" %}
{% block content %}
<h1>Name:</h1>
<p>
    {{ marca.name }}
</p>
<h2>
    Models
     (<a href="{% url 'icars:model_create' %}">add</a>)
</h2>
<ul>
    {% for marca in marca.models.all %}
        <li><a href="{% url 'icars:model_detail' marca.id model.id 'html' %}">
            {{ model.name }}</a></li>
    {% empty %}<li>Sorry, no models for this brand yet.</li>
    {% endfor %}
</ul>

{% endblock %}

cars/icars/templates/icars/marca_list.html
{% extends "icars/base.html" %}
{% block content %}
<h1>
    Marques
    {% if user %}(<a href="{% url 'icars:brand_create' %}">add</a>){% endif %}
</h1>
<ul>
    {% for marca in marques_list %}
        <li><a   <li><a href="{% url 'icars:marca_detail' marca.id 'html' %}">>
            {{ marca.name }}</a></li>
    {% empty %}<li>Sorry, no brands registered yet.</li>
    {% endfor %}
</ul>
{% endblock %}

cars/icars/templates/icars/model_detail.html
{% extends "icars/base.html" %}

{% block content %}

<h1>
    {{ model.name }}
</h1>
<p>{{ model.marca}}</p>

{% endblock %}

cars/icars/templates/icars/model_list.html
{% extends "icars/base.html" %}
{% block content %}
<h1>
    Models
        {% if user %}(<a href="{% url 'icars:model_create' %}">add</a>){% endif %}
</h1>
<ul>
    {% for model in model_list %}
        <li><a>
            {{ model.name }} ({{ model.id }})</a></li>
    {% empty %}<li>Sorry, no models registered yet.</li>
    {% endfor %}
</ul>
{% endblock %}

cars/icars/templates/icars/motor_detail.html
{% extends "icars/base.html" %}

{% block content %}

<h1>
    Motor
</h1>
<h2>
  {{ motor.name }}
</h2>
<p>
  {{ motor.cylinder}} cylinders,
  {{ motor.horsePower}} C,
  {{ motor.fuelType }}:
</p>

{% endblock %}

cars/icars/templates/icars/motor_list.html
{% extends "icars/base.html" %}
{% block content %}
<h1>
    Motors
        {% if user %}(<a href="{% url 'icars:motor_create' %}">add</a>){% endif %}
</h1>
<ul>
    {% for motor in motor_list %}
        <li><a>
            {{ motor.name }},{{ motor.cilinder }},{{ motor.horsePower }},{{ motor.fuelType }} ({{ motor.id }})</a></li>
    {% empty %}<li>Sorry, no motors registered yet.</li>
    {% endfor %}
</ul>
{% endblock %}

cars/icars/templates/icars/style_detail.html
{% extends "icars/base.html" %}
{% block content %}
<span vocab= "http://schema.org/" typeof="Vehicle">
    <h1>
      <span property="name">{{ estil.name }}</span>
    </h1>
  <ul rel="manufacturer">
    <li typeof="Organization">
    	<h2>Make:</h2>
    	<p>
      	<span property="name">{{ estil.make.name }}</span>,
      	<span property="alternateName">{{ estil.make.niceName }}</span>
    	</p>
  	</li>
  </ul>
    <h3>
    Model
    </h3>
  	{% for model in estil.model.all %}
  	<ul rel = "model" >
      <p typeof ="ProductModel" >
        <span property="name">{{ model.name }}</span>
       {% empty %}<li>Sorry, model is not found.</li>
       {% endfor %}
      </p>
    </ul>
    <h3>Year</h3>
        {% for year in estil.year.all %}
        <li property="productionDate">{{ estil.year.year }}</li>
        {% endfor %}

        <h3>Submodel:</h3>
        <p>
          <span property = "alternateName">, {{ estil.submodel.niceName }}</span>
          <span property = "category">, {{ estil.submodel.body }}</span>
          <span property = "fuelType">, {{ estil.submodel.fuel }}</span>
          <span property = "vehicleInteriorType">, {{ estil.submodel.tuner }}</span>
        </p>
</span>
{% endblock %}

cars/icars/templates/icars/style_list.html
{% extends "icars/base.html" %}
{% block content %}
<h1>
    Styles
    {% if user %}(<a href="{% url 'icars:style_create' %}">add</a>){% endif %}
</h1>
<ul>
    {% for estil in style_list %}
        <li><a href="{% url 'icars:style_detail' estil.id 'html' %}">
            {{ estil.name }} ({{ estil.id }})</a></li>
    {% empty %}<li>Sorry, no styles registered yet.</li>
    {% endfor %}
</ul>
{% endblock %}